apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ28tdXNlcg== # required field for kubernetes.io/basic-auth
  mongo-password: bW9uZ28tcGFzc3dvcmQ= # required field for kubernetes.io/basic-auth